services:
  api:
    command: fastapi run app/presentation/api/main.py --host 0.0.0.0 --port 80
    volumes: !reset []

  database:
    volumes: !override
      - /docker_data/postgres:/var/lib/postgresql:rw

  mailcatcher: !reset null

  stripe-cli: !reset null
