name: pro-plan-api

services:
  api:
    build:
      context: .
    command: fastapi dev app/presentation/api/main.py --host 0.0.0.0 --port 80
    container_name: api
    depends_on:
      database:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    environment:
      - API_TOKEN
      - DATABASE_URL
      - STRIPE_API_KEY
      - STRIPE_CHECKOUT_SUCCESS_URL
      - STRIPE_PRICE_ID_MONTHLY
      - STRIPE_PRICE_ID_YEARLY
      - STRIPE_WEBHOOK_SECRET
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./:/code

  database:
    container_name: database
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    image: postgres:18.3
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./.docker/postgres:/var/lib/postgresql

  migrations:
    build:
      context: .
    command: make m
    container_name: migrations
    depends_on:
      - database
    environment:
      - DATABASE_URL
    restart: on-failure:10
    volumes:
      - ./:/code

  stripe-cli:
    command: listen --forward-to api:80/api/stripe/webhooks
    container_name: stripe-cli
    depends_on:
      - api
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY?Stripe API key is required}
    image: stripe/stripe-cli
