name: pro-plan-api

services:
  api:
    build:
      context: .
    command: fastapi dev app/presentation/api/main.py --host 0.0.0.0 --port 80
    container_name: pro-plan-api
    depends_on:
      database:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    ports:
      - '8081:80'
    restart: always
    volumes:
      - ./:/code
      - ./.docker/api:/data

  database:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:18.3
    ports:
      - '54321:5432'
    restart: always
    volumes:
      - ./.docker/postgres:/var/lib/postgresql

  migrations:
    build:
      context: .
    command: make m
    depends_on:
      - database
    restart: on-failure:3
    volumes:
      - ./:/code

  stripe-cli:
    command: listen --forward-to api:80/api/stripe/webhooks
    depends_on:
      - api
    environment:
      - STRIPE_API_KEY
    image: stripe/stripe-cli
