"""add has_active_subscription column

Revision ID: 4f8b0a848b1c
Revises: 5f80b1139f94
Create Date: 2026-07-31 09:00:38.951777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8b0a848b1c"
down_revision: str | Sequence[str] | None = "5f80b1139f94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column(
            "has_active_subscription",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("customer", "has_active_subscription", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer", "has_active_subscription")
    # ### end Alembic commands ###
