"""add customers table

Revision ID: 56b410e0dbf7
Revises:
Create Date: 2026-08-05 14:02:22.660727

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56b410e0dbf7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stripe_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "stripe_subscription_cancel_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "stripe_subscription_current_period_end_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "stripe_subscription_product_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "stripe_subscription_status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="c_ui_external_id"),
        sa.UniqueConstraint("stripe_id", name="c_ui_stripe_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customers")
    # ### end Alembic commands ###
