"""add stripe_product_id column and remove has_pro column

Revision ID: 5f80b1139f94
Revises: b7c31f04a9e2
Create Date: 2026-07-30 12:37:56.230130

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f80b1139f94"
down_revision: str | Sequence[str] | None = "b7c31f04a9e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column(
            "stripe_product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.drop_column("customer", "has_pro")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column("has_pro", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("customer", "has_pro", server_default=None)
    op.drop_column("customer", "stripe_product_id")
    # ### end Alembic commands ###
