"""add stripe_subscription_period_end_at and stripe_subscription_cancel_at columns

Revision ID: 7f789c3958fe
Revises: 451f56bd5a55
Create Date: 2026-08-03 15:03:47.440727

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f789c3958fe"
down_revision: str | Sequence[str] | None = "451f56bd5a55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column(
            "stripe_subscription_period_end_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "customer",
        sa.Column(
            "stripe_subscription_cancel_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer", "stripe_subscription_cancel_at")
    op.drop_column("customer", "stripe_subscription_period_end_at")
    # ### end Alembic commands ###
