"""add stripe_subscription_status column

Revision ID: b2930cf7aa1b
Revises: 5f80b1139f94
Create Date: 2026-07-31 13:51:26.266079

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2930cf7aa1b"
down_revision: str | Sequence[str] | None = "5f80b1139f94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column(
            "stripe_subscription_status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer", "stripe_subscription_status")
    # ### end Alembic commands ###
