"""add stripe_product_id column

Revision ID: c41a45154171
Revises: b7c31f04a9e2
Create Date: 2026-07-30 12:08:40.980575

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c41a45154171"
down_revision: str | Sequence[str] | None = "b7c31f04a9e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column(
            "stripe_product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer", "stripe_product_id")
    # ### end Alembic commands ###
