"""add subscription table

Revision ID: 1cb03f394cd3
Revises:
Create Date: 2026-03-27 09:04:38.771917

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cb03f394cd3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "period", sa.Enum("MONTHLY", "YEARLY", name="period"), nullable=False
        ),
        sa.Column("next_payment_date", sa.Date(), nullable=True),
        sa.Column(
            "state", sa.Enum("NEW", "ACTIVE", "EXPIRED", name="state"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_email"), "subscription", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_next_payment_date"),
        "subscription",
        ["next_payment_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_state"), "subscription", ["state"], unique=False
    )
    op.create_index(
        "uq_subscription_email",
        "subscription",
        ["email"],
        unique=True,
        postgresql_where=sa.text("state IN ('NEW', 'ACTIVE')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_subscription_email",
        table_name="subscription",
        postgresql_where=sa.text("state IN ('NEW', 'ACTIVE')"),
    )
    op.drop_index(op.f("ix_subscription_state"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_next_payment_date"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_email"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
