"""add stripe_customer_id column

Revision ID: 5284f16dd71d
Revises: e1af5e366665
Create Date: 2026-07-13 09:30:05.987244

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5284f16dd71d"
down_revision: str | Sequence[str] | None = "e1af5e366665"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription",
        sa.Column(
            "stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription", "stripe_customer_id")
    # ### end Alembic commands ###
