"""add payment table

Revision ID: 796d5705ab5a
Revises: ac0b5ada818d
Create Date: 2026-03-30 10:26:26.909408

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "796d5705ab5a"
down_revision: Union[str, Sequence[str], None] = "ac0b5ada818d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("paid_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscription.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payment_subscription_id_paid_at_id",
        "payment",
        ["subscription_id", "paid_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payment_subscription_id_paid_at_id", table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
