"""add subscription table

Revision ID: ac0b5ada818d
Revises: 
Create Date: 2026-03-27 15:16:39.875345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ac0b5ada818d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'YEARLY', name='period'), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'ACTIVE', 'EXPIRED', name='state'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_subscription_next_payment_date'), 'subscription', ['next_payment_date'], unique=False)
    op.create_index(op.f('ix_subscription_state'), 'subscription', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_state'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_next_payment_date'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
