"""switch subscription to is_active flag

Revision ID: e1af5e366665
Revises: ac0b5ada818d
Create Date: 2026-07-09 17:19:37.887456

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1af5e366665"
down_revision: str | Sequence[str] | None = "ac0b5ada818d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("subscription", "expires_at")
    op.drop_column("subscription", "period")
    sa.Enum(name="period").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    period_enum = sa.Enum("MONTHLY", "YEARLY", name="period")
    period_enum.create(op.get_bind())
    op.add_column("subscription", sa.Column("period", period_enum, nullable=False))
    op.add_column("subscription", sa.Column("expires_at", sa.Date(), nullable=True))
    op.drop_column("subscription", "is_active")
    # ### end Alembic commands ###
