"""add unique constraint

Revision ID: e9edfee3741b
Revises: 5284f16dd71d
Create Date: 2026-07-16 09:46:04.687844

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e9edfee3741b'
down_revision: str | Sequence[str] | None = '5284f16dd71d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_stripe_customer_id', 'subscription', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stripe_customer_id', 'subscription', type_='unique')
    # ### end Alembic commands ###
